name: _job_schedule_weekly

permissions:
  actions: write
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */7 * *'

jobs:

  mesa-git:
    uses: ./.github/workflows/mesa-git.yml

  wine-cachyos:
    needs: mesa-git
    uses: ./.github/workflows/wine-cachyos.yml

  proton-cachyos:
    needs: wine-cachyos
    uses: ./.github/workflows/proton-cachyos.yml

  proton-cachyos-slr:
    needs: proton-cachyos
    uses: ./.github/workflows/proton-cachyos-slr.yml

  linux-kernel-catgirl:
    needs: proton-cachyos-slr
    uses: ./.github/workflows/linux-kernel-catgirl.yml

  glibc:
    needs: linux-kernel-catgirl
    uses: ./.github/workflows/glibc.yml

  llvm:
    needs: glibc
    uses: ./.github/workflows/llvm.yml

  firefox:
    needs: llvm
    uses: ./.github/workflows/firefox.yml

  chromium:
    needs: firefox
    uses: ./.github/workflows/chromium.yml

  obs-studio:
    needs: chromium
    uses: ./.github/workflows/obs-studio.yml
