name: _job_schedule_biweekly

permissions:
  actions: write
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */13 * *'

jobs:

  7zip:
    uses: ./.github/workflows/7zip.yml

  aria2:
    needs: 7zip
    uses: ./.github/workflows/aria2.yml

  ccache-ext:
    needs: aria2
    uses: ./.github/workflows/ccache-ext.yml

  curl:
    needs: ccache-ext
    uses: ./.github/workflows/curl.yml

  dolphin-emu:
    needs: curl
    uses: ./.github/workflows/dolphin-emu.yml

  ffmpeg:
    needs: dolphin-emu
    uses: ./.github/workflows/ffmpeg.yml

  gamescope:
    needs: ffmpeg
    uses: ./.github/workflows/gamescope.yml

  handbrake:
    needs: gamescope
    uses: ./.github/workflows/handbrake.yml

  heroic-games-launcher:
    needs: handbrake
    uses: ./.github/workflows/heroic-games-launcher.yml

  mpv:
    needs: heroic-games-launcher
    uses: ./.github/workflows/mpv.yml

  prismlauncher:
    needs: mpv
    uses: ./.github/workflows/prismlauncher.yml

  ryujinx:
    needs: prismlauncher
    uses: ./.github/workflows/ryujinx.yml

  svt-av1:
    needs: ryujinx
    uses: ./.github/workflows/svt-av1.yml

  vscode:
    needs: svt-av1
    uses: ./.github/workflows/vscode.yml

  wine-tkg-git:
    needs: vscode
    uses: ./.github/workflows/wine-tkg-git.yml
