name: obs-studio

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      action:
        description: "Repository action"
        required: true
        type: choice
        default: 'build'
        options:
        - 'build'
        - 'remove'
        - 'skip'
  push:
    branches:
     - master
     - main
    paths:
     - obs-studio/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/_job_pkgrepo.yml
    with:
      pkgdir: obs-studio
      repository: ${{ matrix.repository }}
      action: ${{ inputs.action != '' && inputs.action || 'build' }}
